IsTrustedSequencer = false

[Log]
Environment = "development" # "production" or "development"
Level = "info"
Outputs = ["stderr"]

[Synchronizer]
SyncInterval = "3s"
SyncChunkSize = 100
SyncOnlyTrusted = false
TrustedSequencerURL = "https://rpc.merlinchain.io"

[Etherman]
URL = "http://18.142.49.94:8545" # L1 rpc
ForkIDChunkSize = 20000
MultiGasProvider = false

[RPC]
Host = "0.0.0.0"
Port = 8123
ReadTimeout = "60s"
WriteTimeout = "60s"
MaxRequestsPerIPAndSecond = 100
SequencerNodeURI = "https://rpc.merlinchain.io"
EnableL2SuggestedGasPricePolling = false
TraceBatchUseHTTPS = true
    [RPC.WebSockets]
    Enabled = true
    Host = "0.0.0.0"
    Port = 8133

[StateDB]
User = "state_user"
Password = "state_password"
Name = "state_db"
Host = "cdk-validium-state-db"   #Remember to confirm host
Port = "5432"
EnableLog = false
MaxConns = 200

[Pool]
DefaultMinGasPriceAllowed=50000000

[Pool.DB]
User = "pool_user"
Password = "pool_password"
Name = "pool_db"
Host = "cdk-validium-pool-db"
Port = "5432"
EnableLog = false
MaxConns = 200

[Metrics]
Host = "0.0.0.0"
Port = 9091
Enabled = true
ProfilingHost = "0.0.0.0"
ProfilingPort = 6060
ProfilingEnabled = true

[MTClient]
URI  = "cdk-validium-prover:50061"

[Executor]
URI = "cdk-validium-prover:50071"
MaxResourceExhaustedAttempts = 5
WaitOnResourceExhaustion = "1s"
MaxGRPCMessageSize = 100000000